Feature: Dates generated by instalover

  Scenario: Instalover generates dates for users
    Given the following users exist:
      | Phone Number | Male | Female | Looking For Male | Looking For Female | Dob          | Looking For Minimum Age | Looking For Maximum Age | Description | Name  |
      | 11111111111  | true | false  | false            | true               | 11/06/1989   | 18                      | 34                      | red hair    | Mike  |
      | 12222222222  | true | false  | false            | true               | 10/20/1989   | 18                      | 34                      | black shirt | Jason |
      | 18004688487  | false| true   | true             | false              | 12/31/1977   | 14                      | 22                      | super hot   | Emma  |
      | 13333333333  | false| true   | true             | false              | 12/32/1980   | 14                      | 30                      | super hot   | Emma  |
    And the day and time is "October 16, 2010 8:00pm edt"
    And the following date suggestions exist:
      | text             |
      | Silvertone       |
      | Mike's Apartment |
    When I run the rake task "instalover:ping_female_dates"
    Then "13333333333" should get a text whose message includes "Should we find you a date "
    Then "18004688487" should get a text whose message includes "Should we find you a date "

